---
title: "Nothing beats college than college basketball!"
subtitle: "Scott's Data Science Portfolio" 
output:
  html_document:
    df_print: paged
---

## Abstract

I love basketball and wanted to do something based on it. So in this project I am intrested in determining by points and other stats if your on a good team or not. Good teams are often ranked so I want to predict if good stats mean your on a ranked team on not.


### 1. Discovery and Data Preparation

My first dataset contains every player and school in DI for basketball. I will examine the two best conferences in the NCAA and determine the best teams for those conferences based on scoring. Furthermore I will examine games played based on position along with points scored on average by position. The overall scoring average (PPG) between the two best NCAA conferences in the nation (ACC and PAC 12) as well as the number of games each position player plays for the entire NCAA along with how many points each position player scores.

Link: [here](./deliverable1.html)

### 2. Model Planning and Building

The highest scoring players by points and if there on a ranked team or not. This will help us to predict if a high scoring player is on a ranked team or not. It turns out points and other variables were not a good indicator to determine if a player is on a ranked team or not.

Link: [here](./deliverable2.html)

### 3. Results and Operationalization 

My new dataset I added for my new model did not produce useful results. I was hoping my new dataset would yeild more varance but the output of my model and cross-validations were not useful. To operationalize it I believe I needed more data from my third dataset.

Link: [here](./deliverable3.html)


